### ISSUE TITLE
Error when trying to run rip json2pot

### ISSUE THREAD

**Issue by malreynolds** [evenchange4/react-intl-po#32]
Getting the following error, when I run json2pot:
```
/home/atanas/workspace/telematics_signup/spa/node_modules/to-object-by/lib/toObjectBy.js:10
  return array.reduce(function (acc, e) {
               ^

TypeError: array.reduce is not a function
    at toObjectBy (/home/atanas/workspace/telematics_signup/spa/node_modules/to-object-by/lib/toObjectBy.js:10:16)
    at /home/atanas/workspace/telematics_signup/spa/node_modules/react-intl-po/lib/readAllMessageAsObjectSync.js:58:37
    at Array.map (native)
    at readAllMessageAsObjectSync (/home/atanas/workspace/telematics_signup/spa/node_modules/react-intl-po/lib/readAllMessageAsObjectSync.js:55:4)
    at /home/atanas/workspace/telematics_signup/spa/node_modules/lodash/_createFlow.js:75:42
    at Command.extractAndWritePOTFromMessagesSync (/home/atanas/workspace/telematics_signup/spa/node_modules/react-intl-po/lib/extractAndWritePOTFromMessagesSync.js:33:40)
    at Command.listener (/home/atanas/workspace/telematics_signup/spa/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:87:13)
    at Command.emit (events.js:172:7)
    at Command.parseArgs (/home/atanas/workspace/telematics_signup/spa/node_modules/commander/index.js:615:12)
```

Tried both 1.0.6 and 1.0.7, getting the same result. Running this as a npm command in package.json, not sure if it matters:

`"compilemessages": "rip json2pot 'messages/locales/*.json' -o ./translations.pot"`

Thanks!

**Comment by evenchange4** [comment]
I have no idea with those error messages. :(

Would you mind providing the structure of your messages ('messages/locales/*.json')?
Or a standalone repository would be better so that I can reproduce it.

Thanks!

**Comment by malreynolds** [comment]
Hi, that was my bad, I wrongly assumed the package would work on files with structure similar to the one when generated through po2json!

I.e.

```js
{
   "landing.welcomeMessage":"Welcome"
}
```

vs

```js
[
  {
    "id": "landing.welcomeMessage",
    "description": "A welcome message to the users",
    "defaultMessage": "Welcome."
  }
]
```

Either way, thanks for the quick response, pointed me in the right direction.
